<?php
#### Generated by Block Creator by Disipal Site (www.disipal.net) ###
if (eregi("block-Service.php",$PHP_SELF)) {
    Header("Location: index.php");
    die();
}

$content  =  "<center>";

$content  .=  "<a href=\"http://www.evo-hungary.hu/\" title=\"Evo-Hungary\" target=\"_blank\"><img src=\"http://www.evo-hungary.hu/pics/ShotSnap/evohungary.jpg\" width=\"138\" alt=\"Evo-Hungary\" class=\"gradualshine\" onMouseover=\"slowhigh(this)\" onMouseout=\"slowlow(this)\"></a>&nbsp;&nbsp;";

$content  .=  "<a href=\"http://www.evo-hungary.hu/directory/\" title=\"SEO Friendly Evo-Hungary Directory\" target=\"_blank\"><img src=\"http://www.evo-hungary.hu/pics/ShotSnap/directory.jpg\" width=\"138\" alt=\"SEO Friendly Evo-Hungary Directory\" class=\"gradualshine\" onMouseover=\"slowhigh(this)\" onMouseout=\"slowlow(this)\"
></a>&nbsp;&nbsp;";

$content  .=  "<br><br>";

$content  .=  "<a href=\"http://www.evo-hungary.hu/Topsites/\" title=\"Evo-Topsites 4u\" target=\"_blank\"><img src=\"http://www.evo-hungary.hu/pics/ShotSnap/topsites4u.jpg\" width=\"138\" alt=\"Evo-Topsites 4u\" class=\"gradualshine\" onMouseover=\"slowhigh(this)\" onMouseout=\"slowlow(this)\"
></a>&nbsp;&nbsp;";

$content  .=  "<a href=\"http://evothemes.extra.hu/\" title=\"Evolution-Theme-Demo-System\" target=\"_blank\"><img src=\"http://www.evo-hungary.hu/pics/ShotSnap/evothemes.shots.snap.com.jpg\" width=\"138\" alt=\"Evolution-Theme-Demo-System\" class=\"gradualshine\" onMouseover=\"slowhigh(this)\" onMouseout=\"slowlow(this)\"
></a>&nbsp;&nbsp;";

$content  .=  "<br><br>";
$content  .=  "<a href=\"http://wowecommerce.reality.info.hu/\" title=\"WoW eCommerce\" target=\"_blank\"><img src=\"http://www.evo-hungary.hu/pics/ShotSnap/wowecommerce.jpg\" width=\"138\" alt=\"WoW eCommerce\" class=\"gradualshine\" onMouseover=\"slowhigh(this)\" onMouseout=\"slowlow(this)\"></a>&nbsp;&nbsp;";

$content  .=  "<a href=\"http://darkwowweb.extra.hu/\" title=\"WoW Ultimate Revolution - Burning Crusade\" target=\"_blank\"><img src=\"http://www.evo-hungary.hu/pics/ShotSnap/WoWUltimateRevolutionBurningCrusadeShotsSnapCom.jpg\" width=\"138\" alt=\"WoW Ultimate Revolution - Burning Crusade\" class=\"gradualshine\" onMouseover=\"slowhigh(this)\" onMouseout=\"slowlow(this)\"></a>";
$content  .=  "</center>";
?>