<?php
/*=======================================================================
 Nuke-Evolution Basic: Enhanced PHP-Nuke Web Portal System
 =======================================================================*/

/***************************************************************************
      This file was automatically generated by Admin FAQ Editor
 ***************************************************************************/

/***************************************************************************
 *
 *   This program is free software; you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation; either version 2 of the License, or
 *   (at your option) any later version.
 *
 ***************************************************************************/
 
// 
// To add an entry to your FAQ simply add a line to this file in this format:
// $faq[] = array("question", "answer");
// If you want to separate a section enter $faq[] = array("--","Block heading goes here if wanted");
// Links will be created automatically
//
// DO NOT forget the ; at the end of the line.
// DO NOT put double quotes (") in your FAQ entries, if you absolutely must then escape them ie. \"something\"
//
// The FAQ items will appear on the FAQ page in the same order they are listed in this file
//

$faq[] = array("--", "Hozzászólás");
$faq[] = array("Olvasd el a fórumra vonatkozó szabályokat", "[b]1.[/b] Mielõtt felteszed a kérdésed, használd a keresõt.
<br /> 
<br />[b]2.[/b] Hozzászólásod címének [b]NE[/b] használd a következõket:
<br />[list]
<br />[*] SEGÍTSÉG! 
<br />[*] SEGÍTSÉGRE VAN SZÜKSÉGEM! 
<br />[*] Van egy kérdésem. 
<br />[*] NAGY probléma! 
<br />[*] Kezdõ vagyok, segítsetek! 
<br />[*] Problémák 
<br />[*] SÜRGÕS! 
<br />[*] SEGÍTSETEK.[/list]
<br />[b]vagy BÁRMI hasonlót!!! 
<br />[/b]
<br />
<br />[b]KONKRÉT[/b] címet írj, nagyobb az esélyed a segítségre. 
<br />[b]Amennyiben mégis ilyen általános címet használsz, hozzászólásodat ELTÁVOLÍTHATJUK[/b] 
<br />
<br />[b]3.[/b] Segíts, hogy segíthessünk. Hozzászólásodban minél több információt adj meg. 
<br />[list]
<br />[*] Beállítások 
<br />[*] Szoftver verzió 
<br />[*] Konkrét probléma 
<br />[*] Minél részletesebben 
<br />[/list]
<br />
<br />[b]4.[/b] Egy téma 3,  4 vagy 5 alkalommal való küldése nem hoz gyorsabb választ...így talán nem is kapsz választ.
<br /> 
<br />[b]5.[/b] Akkor nyiss új témát, ha szükséges. Ha már van hasonló, akkor abba írj. Ez, a témát a lista elejére helyezi, és így néhány felhasználó téma értesítést is kaphat. 
<br />
<br />[b]6.[/b] Megfelelõ témát a megfelelõ fórumba tedd. 
<br />i.e. Kérést a Kérések fórumába, Off topik az Off topik fórumba. 
<br />Ennek elmulasztása a téma törlését eredményezheti! 
<br />
<br />[b]7.[/b] [b]NE[/b] lépj kapcsolatba az adminisztrátorral, moderátorral E-mailben, vagy Privát üzenetben a kérdéseddel [b]ANÉLKÜL[/b] , hogy Õ erre megkért volna! Az ilyen kérdéseket és üzeneteket [b]NEM[/b] vesszük figyelembe! 
<br />
<br />Megpróbálunk segíteni, amint tudunk. Vedd figyelembe, hogy szabadidõnkben tesszük ezt.");
$faq[] = array("Milyen nyelven írhatok?", "Az oldal alapértelmezett nyelve a Magyar. Mûködik egy Angol chit chat fórum is, de ezt nem használjuk gyakran, mivel csak egy felhasználónk beszéli e nyelvet. Szóval maradjunk a Magyar nyelvnél.");
$faq[] = array("Hogy kérhetek, vagy küldhetek hibajelentést? ", "[i]Kérések:[/i] <br />Add meg a mod nevét <br />Add meg a linket az eredeti modhoz (ahonnan letölthetjük). <br />Írj egy rövid leírást a mod használatáról <br /><br />[i]Hibák:[/i] <br />Küldd el a hibaüzenet szövegét. <br />Bizonyosodj meg róla, hogy a hibakeresés mûködik-e. <br />Írd meg az oldalad linkjét (ahol a hiba elõjött). ");

$faq[] = array("--", "Egyéb szabályok");
$faq[] = array("Spam", "Ne spammelj a fórumban. A moderátorok kitiltják a spammelõ felhasználókat!");
$faq[] = array("Felhasználónév", "Használj \"valós\" felhasználónevet! Minden olyan felhasználónevet, amely valamely ismert ember neve, rasszista felhangú, reklámcélokat szolgál vagy trágár kifejezés, bannolni fogunk! ");
$faq[] = array("Kapcsolat az adminisztrátorokkal, moderátorokkal.", "Ne lépj kapcsolatba az adminisztrátorokkal, moderátorokkal:<br />- [b]E-mailben[/b]<br />- [b]MSN,AIM, Yahoo Messenger, ICQ[/b]<br />- [b]Privát üzenetben[/b]<br /><br />[b]CSAK[/b] abban az esetben, ha Õk erre megkérnek. Minden nem kívánatos üzenetet figyelmen kívûl hagynak. <br /><br />");
$faq[] = array("Mi a bumpolás?", "Ha kértél/küldtél hibajelentést és már jóideje nem reagáltunk rá, akkor használhatod ezt, ehelyett: <br /><br />SEGÍTSETEK! (példa). <br /><br />Elõfordulhat, hogy 2-3 napba telik, mire [b]EGY[/b] figyelmeztetést kapsz, ha visszaélsz ezzel. Ha közben újra megteszed, vagy spammelsz, [b]KI LESZEL TILTVA![/b] <br /><br />Értsd meg, [b]NEKÜNK[/b] is van magánéletünk, és nem tudunk minden alkalommal azonnal válaszolni! ");
$faq[] = array("Spammelés Privát üzenetben", "Reklámok küldése Privát üzenetben nem megengedett. Ellenõrizzük az üzeneteket, hogy a szabályoknak megfelelõek-e. Ha észrevesszük, hogy valaki reklámot küld, vagy errõl értesítenek bennünket, az ip címed minden figyelmeztetés nélkül, végérvényesen letiltjuk. [b]NEM FOGUNK FIGYELMEZTETNI[/b] , és kitiltunk, valamint a szolgáltatóddal is felvesszük a kapcsolatot! [b]MI FIGYELMEZTETTÜNK[/b]");



?>
